from datetime import datetime, timezone
from typing import List, Dict, Any, Optional, Union
from pydantic import BaseModel, Field


class ColumnProfile(BaseModel):
    """
    Detailed statistical and schema profile for an individual column in a dataset.
    """
    original_name: str = Field(..., description="The original raw column name from the CSV.")
    normalized_name: str = Field(..., description="The normalized snake_case name used internally.")
    column_position: int = Field(..., description="The 0-indexed column offset in the CSV headers.")
    detected_data_type: str = Field(..., description="Detected logical datatype (e.g. INTEGER, EMAIL).")
    storage_type: str = Field(..., description="Physical type representation in Python/Pandas.")
    semantic_hint: str = Field("", description="Clinical or domain semantic categorization hint (empty for now).")
    nullable: bool = Field(..., description="Flag indicating if the column contains missing or null values.")
    unique_count: int = Field(..., description="Count of distinct non-null values.")
    duplicate_count: int = Field(..., description="Count of duplicate cell values in the column.")
    missing_count: int = Field(..., description="Count of missing/null values.")
    missing_percentage: float = Field(..., description="Percentage of cell values that are missing (0.0 to 100.0).")
    
    # Statistical summaries (populated where datatype appropriate, else None)
    min_value: Optional[Union[float, int, str]] = Field(None, description="Minimum value found.")
    max_value: Optional[Union[float, int, str]] = Field(None, description="Maximum value found.")
    mean: Optional[float] = Field(None, description="Arithmetic mean (numeric columns only).")
    median: Optional[float] = Field(None, description="Median value (numeric columns only).")
    std_dev: Optional[float] = Field(None, description="Standard deviation (numeric columns only).")
    mode: Optional[Union[float, int, str]] = Field(None, description="Most frequently occurring value.")
    sample_values: List[Union[float, int, str]] = Field(default_factory=list, description="Sample of the first 10 unique values.")
    
    # Structural details
    memory_usage: int = Field(..., description="Memory footprint in bytes used by this column.")
    cardinality: str = Field(..., description="Cardinality label: 'constant', 'binary', 'low', 'medium', or 'high'.")


class DataQualityIssue(BaseModel):
    """
    Data quality issue details identified in the dataset during profiling.
    """
    column: Optional[str] = Field(None, description="The column affected by the quality issue, or None for dataset-level.")
    issue_type: str = Field(..., description="Categorization of the issue (e.g., 'missing_values', 'outliers').")
    severity: str = Field(..., description="Severity level: 'info', 'warning', 'critical'.")
    message: str = Field(..., description="Detailed, descriptive message explaining the issue.")
    affected_percentage: float = Field(default=0.0, description="Percentage of rows or elements affected.")


class DatasetProfile(BaseModel):
    """
    Comprehensive, dataset-level metadata and quality metrics generated by the profiling engine.
    """
    dataset_id: str = Field(..., description="UUID of the profiled dataset.")
    rows: int = Field(..., description="Total row count.")
    columns_count: int = Field(..., description="Total column count.")
    total_missing_values: int = Field(..., description="Total missing cell count across the entire dataset.")
    duplicate_rows: int = Field(..., description="Total count of duplicate data rows.")
    memory_usage: int = Field(..., description="Total memory footprint in bytes.")
    estimated_dataset_size: str = Field(..., description="Human-readable memory size string (e.g. '1.5 MB').")
    delimiter: str = Field(..., description="The field separator character.")
    encoding: str = Field(..., description="Detected text character encoding.")
    
    # Column Type Aggregates
    numeric_column_count: int = Field(0, description="Number of numeric columns.")
    categorical_column_count: int = Field(0, description="Number of categorical columns.")
    date_column_count: int = Field(0, description="Number of date/datetime columns.")
    text_column_count: int = Field(0, description="Number of free-text columns.")
    boolean_column_count: int = Field(0, description="Number of boolean columns.")
    
    # Downstream Semantic Role Recommendations
    potential_target_columns: List[str] = Field(default_factory=list, description="Columns representing labels or outcomes.")
    potential_identifier_columns: List[str] = Field(default_factory=list, description="Columns representing patient or session keys.")
    potential_time_columns: List[str] = Field(default_factory=list, description="Columns carrying date or timestamp profiles.")
    potential_measurement_columns: List[str] = Field(default_factory=list, description="Columns carrying clinical metrics.")
    
    # Quality & Mapping details
    dataset_quality_score: float = Field(..., description="Dataset quality score from 0.0 (poor) to 100.0 (flawless).")
    quality_issues: List[DataQualityIssue] = Field(default_factory=list, description="List of all detected data quality issues.")
    columns: Dict[str, ColumnProfile] = Field(..., description="Map of normalized column names to their profiles.")
    created_at: datetime = Field(default_factory=lambda: datetime.now(timezone.utc), description="Profile generation timestamp.")


class ProfileResponse(BaseModel):
    """
    API Response model wrapper returning the dataset profile.
    """
    dataset_id: str = Field(..., description="The profiled dataset UUID.")
    profile: DatasetProfile = Field(..., description="The generated dataset profile.")
    recalculated: bool = Field(False, description="Flag indicating if the profile was rebuilt or fetched from cache.")
